services:
  server1:
    image: app-test:latest
    pull_policy: always
    container_name: ManagedServer
    hostname: ManagedServer
    privileged: true
    stdin_open: true
    tty: true
    cpus: "4.0"
    mem_limit: "8g"
    shm_size: "2g"
    ports:
      - "28080:8080"  # hostPort:containerPort
    environment:
      - JVM_OPT=-Xms2048m -Xmx2048m
    volumes:
      - ../LOG/ManagedServer:${JEUS_HOME}/logs:rw   # ← volumes 키 추가
    networks:
      - tmaxsoft-network
    restart: unless-stopped

    #entrypoint: ["start.sh"]
    #tmpfs:
    #  - ${JEUS_HOME}/domains/jeus_domain/servers:size=2g
    #platform: linux/amd64
    #ulimits:
    #  nofile:
    #    soft: 65536
    #    hard: 65536

networks:
  tmaxsoft-network:
    external: true
