services:
  node01:
    image: app-test:latest
    #pull_policy: always
    #entrypoint: ["start.sh"]
    container_name: ManagedServer
    hostname: ManagedServer
    platform: linux/amd64
    privileged: true
    stdin_open: true
    tty: true
    cpus: "4.0"
    mem_limit: "8g"
    shm_size: "2g"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - JVM_OPT=-Xms2048m -Xmx2048m
    volumes:
      - ../LOG/ManagedServer:${JEUS_HOME}/logs:rw   # ← volumes 키 추가
    networks:
      - tmaxsoft-network
    restart: unless-stopped

networks:
  tmaxsoft-network:
    external: true
